#!/bin/bash
curl -o spark.tgz https://dlcdn.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-without-hadoop.tgz
tar zxf spark.tgz
mv spark-3.2.0-bin-without-hadoop spark
cd spark
curl -o mysql.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar
mv mysql.jar jars/mysql.jar
curl -o spark-streaming-kinesis-asl-assembly_2.12-3.3.0.jar http://ss-utopia-build-resources.s3.amazonaws.com/jars/spark-streaming-kinesis-asl-assembly_2.12-3.3.0.jar
mv spark-streaming-kinesis-asl-assembly_2.12-3.3.0.jar jars/spark-streaming-kinesis-asl-assembly_2.12-3.3.0.jar